install.packages('markdown')
install.packages('rmarkdown')
install.packages("devtools")
install.packages("XML")
install.packages("diffr")
install.packages("tools")
#install.packages("diffobj")
library(devtools)
install.packages("tinytex")
tinytex::install_tinytex()  # install TinyTeX for generate PDF
install.packages("gridExtra")
install.packages("tidyverse")
devtools::install_github("r-lib/crayon")
devtools::install_github("hadley/emo")
